(function(){var d=void 0,h=true,i=null,j=false;function k(){return function(){}}function m(a){return function(){return this[a]}}function p(a){return function(){return a}}var q,r=this;
function ba(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ca(a,b,c){return a.call.apply(a.bind,arguments)}function da(a,b,c){if(!a)throw Error();if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function s(a,b,c){s=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ca:da;return s.apply(i,arguments)}function ea(a,b){function c(){}c.prototype=b.prototype;a.ia=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ga(){}
function ja(a,b,c){switch(typeof b){case "string":ka(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==i){c.push("null");break}if(ba(b)=="array"){var e=b.length;c.push("[");for(var f="",g=0;g<e;g++)c.push(f),ja(a,b[g],c),f=",";c.push("]");break}c.push("{");e="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(g=b[f],typeof g!="function"&&(c.push(e),ka(f,c),c.push(":"),ja(a,g,c),e=","));
c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var la={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},ma=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function ka(a,b){b.push('"',a.replace(ma,function(a){if(a in la)return la[a];var b=a.charCodeAt(0),f="\\u";b<16?f+="000":b<256?f+="00":b<4096&&(f+="0");return la[a]=f+b.toString(16)}),'"')};var na={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3};function oa(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function pa(a,b){var c="",e=qa(encodeURIComponent(a));e.splice(b||5,e.length);t(e,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",e;a>0;)e=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(e)+b,a>>>=6;a=b}c+=a});return c}
function qa(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,e=4023233417,f=2562383102,g=271733878,l=3285377520,o=[],n,C,E,Q,T,fa=Math.ceil((a.length/4+2)/16),aa=[fa],K=0,D;K<fa;K++){aa[K]=[];for(n=0;n<16;n++)aa[K][n]=a.charCodeAt(K*64+n*4)<<24|a.charCodeAt(K*64+n*4+1)<<16|a.charCodeAt(K*64+n*4+2)<<8|a.charCodeAt(K*64+n*4+3)}K=(a.length-1)*8;a=fa-1;aa[a][14]=Math.floor(K/Math.pow(2,32));aa[a][15]=K&4294967295;for(K=0;K<fa;K++){for(D=0;D<16;D++)o[D]=
aa[K][D];for(D=16;D<80;D++)o[D]=(o[D-3]^o[D-8]^o[D-14]^o[D-16])<<1|(o[D-3]^o[D-8]^o[D-14]^o[D-16])>>>31;a=c;n=e;C=f;E=g;Q=l;for(D=0;D<80;D++)T=Math.floor(D/20),T=(a<<5|a>>>27)+(T==0?n&C^~n&E:T==1?n^C^E:T==2?n&C^n&E^C&E:n^C^E)+Q+b[T]+o[D]&4294967295,Q=E,E=C,C=n<<30|n>>>2,n=a,a=T;c=c+a&4294967295;e=e+n&4294967295;f=f+C&4294967295;g=g+E&4294967295;l=l+Q&4294967295}return[c,e,f,g,l]}
function ra(a){var b=r.navigator,c=r.window.screen,e=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];t(b.plugins,function(a){e.push(a.name+a.description+a.filename+a[0].type)});b=r.performance;e=e.concat([b&&b.now?b.now():"",document.title,r.location.href,u(),oa()]);return e.concat(a||[]).join()}function v(a,b,c){var e=Array.prototype.slice,f=e.call(arguments,2);return function(){return a.apply(b,f.concat(e.call(arguments)))}}
function w(a){return typeof a!=="undefined"}function x(a){return a&&a.replace(/^www\./,"")}var sa=/^((https?\:)?(\/\/))/i;function ta(a){return a&&a.replace(sa,"")}var ua=/^((https?\:)?(\/\/))?[^\/]*/;function va(a){return a.replace(ua,"")}var wa=/\#.*/;function xa(a){return a.replace(wa,"")}var za=/\?[^\#]*/;function Aa(a){return a.toLowerCase()}var Ba=/\/+((\?|\#).*)?$/;function Ca(a){return a.replace(Ba,"$1")}function Da(a){return a&&a.replace(za,"")}
function Ea(a){var b=a.match(/\?(.*)$/ig)?a.match(/\?(.*)$/ig)[0].slice(1).replace(/#(.*)?/ig,"").split("&"):[],c=a.match(/#(.*)$/ig)?a.match(/#(.*)$/ig)[0]:"",a=a.match(/[#|\?](.*)?/ig)?a.slice(0,a.search(/[#|\?](.*)?/ig)):a,b=Fa(b,function(a){return a.search("utm")!==0});b.length>0&&(a+="?"+b.join("&"));return a+c}function Ga(a,b){if(a===b)return 0;var c=i;t([Aa,Ca,ta,va,xa,Da],function(e,f){a=e(a);b=e(b);if(a===b)return c=f+1,j});return c}
function Ha(a,b,c,e){a.addEventListener?a.addEventListener(b,c,!!e):a.attachEvent&&a.attachEvent("on"+b,c)}function Ia(a,b,c){a.removeEventListener?a.removeEventListener(b,c,j):a.detachEvent&&a.detachEvent("on"+b,c)}function Ja(a){return typeof a==="number"}function Ka(a){return typeof a==="string"}function La(a){return typeof a==="function"}function Ma(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function u(){return(new Date).getTime()}
function Na(a){return encodeURIComponent(a)}function Oa(){return r.location.protocol==="http:"?"http:":"https:"}function Pa(a){return!!a&&a.constructor===Object}function t(a,b){if(Pa(a)===h)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var e=a.length;c<e;c++)if(b(a[c],c)===j)break}}function Qa(a,b){for(var c=0,e=a.length;c<e;c++)if(b(a[c]))return c;return-1}function Ra(a){var b=r.pSUPERFLY_video,a=Qa(b,a);if(a>-1)return b[a]}
function Fa(a,b){var c=[];t(a,function(a){b(a)&&c.push(a)});return c}function Sa(a){return a===d?0:u()-a}function Ta(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],e=0,f=b.length;e<=f;e++)c[e]=[e];for(var g=0,l=a.length;g<=l;g++)c[0][g]=g;for(var o,n,C,e=1;e<=f;e++)for(g=1;g<=l;g++)o=e-1,n=g-1,C=c[o][n],b.charAt(o)==a.charAt(n)?c[e][g]=C:(n=c[e][n]+1,o=c[o][g]+1,C+=2,c[e][g]=Math.min(n,o,C));return c[b.length][a.length]}
function Ua(a){return a===d?0:u()-a}function Va(a){return Math.round(a===-1||isNaN(a)?-1:a*1E3)}var Wa;function Xa(){}var Ya=r.setInterval,Za=r.clearInterval,$a=r.setTimeout,ab=r.clearTimeout;function bb(a,b){return Ya(a,b)}function cb(a){switch(a){case d:return"undefined";case "":return"empty";default:return a}}function db(a){switch(a){case "undefined":break;case "empty":return"";default:return a}};function eb(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace(/\+/g," "),t(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function fb(a,b){var c="",e=r.location.href.match(/[^?]+[?]([^#]+).*/);if(e){var e=eb(e[1]),f=b||a;e[f]&&(c=e[f])}return encodeURIComponent(c)}function gb(a,b){return!b?h:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function hb(a){var b=[];t(ib,function(c){var e=a[c];w(e)&&(Object.prototype.toString.call(e)==="[object Array]"?t(e,function(a){b.push(c+"="+a)}):Pa(e)?t(e,function(a,c){b.push(c+"="+a)}):((e+"").length||c=="r")&&b.push(c+"="+e))});b.push("_");return b.join("&")}
function jb(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),e=r.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0&&a.indexOf("app:")<0)if(a.indexOf("//")===0)a=e.protocol+a;else if(a.indexOf("/")===0)var f=gb(e.protocol,e.port)?"":e.port,a=e.protocol+"//"+e.hostname+(f?":"+f:"")+a;else{var f=document.baseURI||e.href,g=f.indexOf("?");g===-1&&(g=f.indexOf("#"));if(g===-1)g=f.length;g=f.lastIndexOf("/",g);a=g===-1?
"/"+a:f.substr(0,g)+"/"+a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=e.hostname;if(b.protocol==="")b.protocol=e.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(gb(b.protocol,b.port)||b.port==="0")b.port="";return b}
function kb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function lb(a,b,c,e){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+(a+(e?'="'+e+'"':""))+"]");for(var f=[],b=c.getElementsByTagName(b),c=b.length,g="";c--;)(g=b[c].getAttribute(a))&&(!e||g===e)&&f.push(b[c]);return f}function mb(a,b,c){c=c||"";if(a===d)a=j;else{var e;if(!(e=c===""&&a.getAttribute(b)))if(e=a.getAttribute(b))e=a.getAttribute(b)===c;a=e?a:a===document.body?j:mb(a.parentNode,b,c)}return a}
function nb(a){var b,c;b="pageYOffset";c="scrollTop";if(a&&(a=lb("data-cb-scroll-element"))&&a.length)return a[0][c];if(Ja(r[b]))return r[b];else if(document.body&&document.body[c])return document.body[c];else if(document.documentElement[c])return document.documentElement[c];return 0}function ob(){var a=document,a=a[a.compatMode==="CSS1Compat"?"documentElement":"body"].clientHeight||0;window.innerHeight&&(a=Math.min(window.innerHeight,a));return a}
function pb(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function qb(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return i;var e=a.ownerDocument.documentElement,f=0,g=w(c)?c+1:-1;Ka(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==e&&f!==g;){if(c(a))return a;a=a.parentNode;f++}return i}
function rb(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}function sb(a){a=a||window.event;return!a?i:qb(a.target||a.srcElement,rb,10)}function tb(a,b){var c=document.createElement(a);t(b,function(a,b){c.setAttribute(b,a)});return c};function ub(){this.ma={};this.Ya=1}function vb(a,b,c,e){a.Ya++;a.ma[b]=a.ma[b]||{};a.ma[b][a.Ya]=[c,e];return a.Ya}function wb(a,b){if(Ka(b))a.ma[b]=d,delete a.ma[b];else if(Ja(b)){var c=h;t(a.ma,function(a){t(a,function(f,g){if(parseInt(g,10)===b)return a[g]=d,delete a[g],c=j});return c})}}ub.prototype.Ha=function(a,b){if(this.ma[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];t(this.ma[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
ub.prototype.addEventListener=function(a,b){var c=vb(this,a,b);b._cbEventId=c};ub.prototype.removeEventListener=function(a,b){this.ma[a]&&this.ma[a][b._cbEventId]&&this.ma[a][b._cbEventId][0]===b&&wb(this,b._cbEventId)};var y=new ub;var z={};
z.N=function(){z.Tb?z.wb("pageload"):(z.cd=[{target:r,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:r,event:"resize"},{target:document.body,event:"mousedown"}],z.Db=i,z.Va=i,z.Sb={},z.Ec={},t(z.cd,function(a){var b=a.event;Ha(a.target,b,function(a){z.wb.call(z,b,a)})}),vb(y,"f",function(){z.wb("focus")}),z.wb("pageload"),Ha(document.body,"click",function(a){(a=sb(a))&&y.Ha("c",a)},h),Ha(document.body,"contextmenu",function(a){(a=sb(a))&&y.Ha("r",
a)}),z.Tb=h)};z.hd=function(){var a,b=z.Ec.keydown;if(b===d)return j;b=u()-b;return b<=(a||15E3)&&b>=0};z.rc=100;z.wb=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}z.ue(a);if(z.Db===i)z.Uc(a);else if(!z.Va||na[z.Va]<na[a])z.Va=a};z.ue=function(a){z.Ec[a]=u()};z.Uc=function(a){z.Db=$a(z.pd,z.rc);y.Ha("a");z.Sb[a]!==i&&ab(z.Sb[a]);z.me(a)};
z.me=function(a){var b=z.Sb;b[a]=$a(function(){ab(b[a]);delete b[a];var c=j;t(b,function(){c=h;return j});c||y.Ha("i")},na[a]+z.rc)};z.pd=function(){ab(z.Db);z.Db=i;if(z.Va)z.Uc(z.Va),z.Va=i};var xb,yb,zb,Ab,Bb;(function(){var a,b;t(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof r.document[a]==="boolean")return b=c,j});b!==d&&(Ab=a,Bb=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),zb=b+"visibilitychange")})();var Cb=j;function Db(){Cb=Bb&&r.document[Bb]==="prerender"?h:j}function Eb(){yb=h;y.Ha("f")}function Fb(){yb=j;y.Ha("b")}
function Gb(a,b,c){r.addEventListener?r.addEventListener(a,c,j):r.document.attachEvent&&r.document.attachEvent(b,c)}function Hb(){var a=h;r.document.hasFocus&&(a=r.document.hasFocus());var b=j;Ab&&(b=r.document[Ab]);return a&&!b}function Ib(){Hb()?Eb():Fb()}function Jb(a){Db();if(Cb){var b=j,c=function(){b||(Db(),Cb||(b=h,a(),r.window.setTimeout(function(){r.document.removeEventListener(zb,c,j)},100)))};r.document.addEventListener(zb,c,j)}else a()};function Kb(){this.k=r._sf_async_config||{};this.zc=v(this.Lc,this)}Kb.prototype.N=function(){this.Nc=0};Kb.prototype.Lc=k();Kb.prototype.hb=function(a){if(!Cb){var b=this.zc,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};Kb.prototype.ya=function(){this.zc=i};var A="path",B="domain",Lb="useCanonical",Mb="useCanonicalDomain",Nb="title",Ob="virtualReferrer";function F(a,b,c){a[b]=a[b]||c}function Pb(a,b){for(var c=r[a]||[];c.length;)b(c.shift());r[a]={push:b}}function Qb(a){t(document.getElementsByTagName("script"),function(b){if(typeof b.src==="string"&&b.src.match(/chartbeat.js/))return b=eb(b.src.split("?")[1]),F(a,"uid",b.uid),F(a,B,b.domain),j})}function Rb(a,b){return a[b]?encodeURIComponent(a[b]):""}
function Sb(a){var b={};t(a,function(a,e){e.charAt(0)=="_"&&(b[e]=a)});return b};var G={};G.ld=function(a){try{G.create("_cb_test","1",1,a);var b=G.D("_cb_test");G.remove("_cb_test",a);return b==="1"}catch(c){return j}};G.D=function(a){a+="=";var b="";t(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
G.create=function(a,b,c,e){var f=r._sf_async_config;if(f&&f.noCookies)return"";f=new Date;f.setTime(u()+c*1E3);a=a+"="+b+("; expires="+f.toGMTString())+("; path="+e);return document.cookie=a};G.remove=function(a,b){return G.D(a)?G.create(a,"",-86400,b):""};var H={};H.Y=function(a){var b=r._sf_async_config;if(!a&&b&&b.noCookies)return i;if(H.Y.Jb!==d)return H.Y.Jb;var a=u()+"",c,e;try{if((e=r.localStorage).setItem(a,a),c=e.getItem(a)===a,e.removeItem(a),c)return H.Y.Jb=e}catch(f){}return H.Y.Jb=i};H.D=function(a){var b=H.Y();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&u()>c)?(H.remove(a),""):b.getItem(a)||""};
H.create=function(a,b,c){var e=H.Y();if(e){var f=new Date;f.setTime(u()+c*1E3);try{e.setItem(a,b),e.setItem(a+"_expires",f.getTime())}catch(g){}}};H.remove=function(a){var b=H.Y();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function Tb(a,b){this.yb=a||"";this.xa=b||"/";this.qd=H.Y()!==i||G.ld(this.xa);this.kc=j;Ub(this)}q=Tb.prototype;q.isSupported=m("qd");
function Ub(a){if(!G.D("_cb_ls")){var b=H.Y()!==i,c=G.D("_SUPERFLY_lockout");c&&t(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,h)});var e=G.D("_chartbeat3");e&&(a.create("_v__chartbeat3",e,34128E3,h),G.remove("_chartbeat3",a.xa));b&&((b=G.D("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,h),(b=G.D("_chartbeat5"))&&a.create("_chartbeat5",b,60,h));G.create("_cb_ls","1",34128E3,a.xa)}}function Vb(a){var b=a.kc;a.kc=j;return b}
q.create=function(a,b,c,e){a=e?a:this.yb+a;(H.Y()?H:G).create(a,b,c,this.xa);H.Y()&&G.create(a,b,c,this.xa)};q.update=function(a,b,c,e,f,g,l){a=e?a:this.yb+a;f=Ka(f)?f:"::";e=(e=this.D(a,h))?e.split(f):[];if(l&&e.length){var o=l(b),n=Qa(e,function(a){return l(a)===o});n!==-1&&e.splice(n,1)}e.push(b);for(Ja(g)&&e.length>g&&e.splice(0,e.length-g);e.length>1&&e.join(f).length>4E3;)e.shift();this.create(a,e.join(f),c,h)};
q.D=function(a,b){var a=b?a:this.yb+a,c=(H.Y()?H:G).D(a);if(!c&&H.Y()&&(c=G.D(a))&&G.D("_cb_ls")){this.kc=h;var e;switch(a){case "_SUPERFLY_lockout":e=600;break;case "_chartbeat4":e=60;break;case "_cb_cp":e=60;break;case "_chartbeat3":e=34128E3;break;default:e=34128E3}H.create(a,c,e)}return c};q.remove=function(a,b){a=b?a:this.yb+a;(H.Y()?H:G).remove(a,this.xa);H.Y()&&G.remove(a,this.xa)};function Wb(a){var b=i;if(a&&(b=Xb(),b=!b?b:I(b.pathname)+b.search+b.hash))return b;var c=r.location,b=I(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),e=/&utm_[^=]+=[^&]+/ig;(c=e.exec(c.search))&&(a=a.replace(e,""));e=/\?utm_[^=]+=[^&]+(.*)/i;(c=e.exec(a))&&(a=a.replace(e,c[1]!=""?"?"+c[1]:""));return b+a}function Yb(a){return a&&(a=Xb(),a=!a?a:a.hostname)?a:r.location.hostname}function Xb(){var a=Zb();return!a?a:jb(a.href)}
function Zb(){var a=i;t(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return a=b,j});return a}for(var $b={},ac=0;ac<81;ac++)$b["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(ac)]=h;function bc(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return $b[c]?String.fromCharCode(c):"%"+b.toUpperCase()}
function I(a){if(!Ka(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,bc);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function J(a,b){var c=L();return w(b)&&!w(c[a])?b:c[a]}function L(){w(r._cb_shared)||(r._cb_shared={});return r._cb_shared};var M={ed:{IDLE:0,ze:1,ye:2,dd:3},qa:0};M.N=function(){if(!M.Tb)vb(y,"a",M.yd,M),vb(y,"i",M.Bd,M),vb(y,"f",M.Ad,M),vb(y,"b",M.zd,M),M.Tb=h};M.H=function(){return M.qa};M.yd=function(){M.qa===1?M.Ca(3):M.qa===0&&M.Ca(2)};M.Bd=function(){M.qa===3?M.Ca(1):M.qa===2&&M.Ca(0)};M.Ad=function(){(M.qa===0||M.qa===2)&&M.Ca(3)};M.zd=function(){M.qa===3?M.Ca(2):M.qa===1&&M.Ca(0)};M.Ca=function(a){M.qa=a;y.Ha("s",a)};function cc(a,b){this.Rb=a||d;this.$b=b||d;this.ab=this.Xa=0;this.Gd=v(this.Hd,this);this.Wc=this.Wa=i}q=cc.prototype;q.N=function(){this.ab=this.Xa=0;this.Wa=i;this.Wc=vb(y,"s",this.Dc,this);this.Dc(M.H())};q.Dc=function(a){Za(this.Wa);this.Wa=i;if(a===M.ed.dd)this.Wa=Ya(this.Gd,1E3)};q.Hd=function(){if(this.Rb===d||this.Rb())this.Xa++,this.ab++,this.$b&&this.$b()};q.terminate=function(){Za(this.Wa);this.Wa=i;wb(y,this.Wc)};q.ya=function(){this.terminate();this.$b=this.Rb=d};function dc(){Kb.call(this);this.Ka=[];this.q=new Tb(this.Xc,this.k.cookiePath||"/");this.q.remove("_SUPERFLY_nosample");this.la=new cc;this.bc=v(this.fb,this);Ha(r,"unload",this.bc);Jb(v(this.N,this));this.Ub=j}ea(dc,Kb);q=dc.prototype;q.ic=h;
q.N=function(){dc.ia.N.call(this);this.rb=this.Na=0;this.Ua=u();this.Ba=pa(ec(this));this.gc=h;this.tb=72E5;if(this.ic){var a=+this.k.sessionLength;if(!isNaN(a))this.tb=a*6E4}a=J("d");if(!a){var a=[],b=this.q.D("_chartbeat2",h);b.length>0&&(a=b.split("."));a.length>6&&(a=[]);var b=u(),c=this.q.D("_cb",h);c.length>0?a[1]=a[1]||b:c=a[0];a[0]="";var e=b-+(a[1]||0),f=b-+(a[2]||0);L().n=c&&e>18E5&&f<2592E6?0:1;var e=a[4],g=parseInt(a[5],10)||0;if(!(f=f>18E5))if(fc(this))f=j;else{var f=gc(this),f=decodeURIComponent(f),
f=hc(f)||f,l;l=ic(this);l=decodeURIComponent(l);l=hc(l)||l;f=f!==l}!e||f?(e=pa(ec(this)),a[4]=e,g=1,this.q.remove("_cb_svref",h)):g+=1;a[5]=g;g="1";f=a&&+a[2];e=a&&a[3];if(a&&f&&e)if(g=Math.abs((Ma(b)-Ma(f))/864E5)){g=Math.min(g,16)-1;for(f="";g--;)f+=0;g=(e+f+"1").slice(-16)}else g=e;e=g;c||(c=this.k.utoken||pa(ec(this),3),a[1]=b);a[2]=b;a[3]=e;this.k.utoken=this.jb;this.q.create("_cb",c,34128E3,h);this.q.create("_chartbeat2",a.join("."),34128E3,h);a[0]=c;L().d=a}this.Ge=a.join(".");var o;c=+a[1];
e=+a[2];if((b=a[3])&&c&&e)o=(Math.min((Math.abs((Ma(e)-Ma(c))/864E5)||0)+1,16,b.length)-1).toString(16),o+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.Cc=o;this.Xb=J("n",1);this.jb=a[0];this.qe=a[4];this.oe=a[5];this.pe=ic(this);this.q.create("_cb_svref",ic(this)||"null",1800,h);this.la.N();M.N();z.N();xb||(yb=Hb(),zb&&r.document.addEventListener&&r.document.addEventListener(zb,Ib,j),Gb("focus","onfocusin",Eb),Gb("blur","onfocusout",Fb),yb&&Eb(),xb=h);this.cb=0;this.gd=vb(y,"a",this.Md,this)};
function jc(a){if(!a.q.D("_SUPERFLY_lockout")&&!Cb)a.Jd?a.Ab():(a.Jd=h,!r._sf_async_config&&!r._cbq?(a.xb=v(a.Ab,a),Ha(r,"load",a.xb)):a.Ab())}q.Ab=function(){this.gb=kc();z.N();this.qb=bb(v(this.na,this),15E3);this.na()};
q.na=function(){var a=this.la.ab,a=this.k.reading&&+this.k.reading||a>0;if(this.rb<this.Na&&!a)this.rb++;else{var b;if(Wa===d)b=r.navigator.userAgent,Wa=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=Wa;b&&!a?this.rb++:(a?this.Na=0:this.Ib(),this.rb=0,this.Ka.push(0),this.Ka.length>18&&this.Ka.shift(),this.ic&&u()-this.Ua>=this.tb?this.terminate():this.Sa())}};
q.Lc=function(){this.Ka.push(1);var a=0;t(this.Ka,function(b){a+=b});a<3?(this.gc=h,this.Ib()):(this.terminate(),this.q.create("_SUPERFLY_lockout","1",600))};q.fb=k();q.Md=function(){var a=lc(this);this.cb=Math.max(this.cb,a)};function lc(a){return Math.floor(nb(!!a.k.scrollElement))}q.Ib=function(){var a=this.Na;this.Na=a=a?Math.min(a*2,16):1};q.pb=function(){this.fb();this.terminate()};q.Bb=function(){this.Ub=h;this.N();jc(this)};
function fc(a){if(a.k[Ob])return h;if(mc(a))return j;a=document.referrer.indexOf("://"+r.location.hostname+"/");return a!=-1&&a<9}function mc(a){var b=a.k.referrerOverrideQueryParam,c="";t(window.location.search.substr(1).split("&"),function(a){a=a.split("=");if(a.length==2&&a[0]==b&&a[1])return c=decodeURIComponent(a[1]).replace(/\+/g," "),j});c&&c.indexOf("::")==-1&&(c="external::"+c);return c}
function gc(a){a=a.k[Ob]||mc(a);if(!a&&(a=document.referrer||"")&&!/^(android-)?app:/.test(a)){var b=jb(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=I(b.pathname),a=kb(b)}return encodeURIComponent(a)}function nc(a){a=a.k[Nb].slice(0,100);return encodeURIComponent(a)}function ec(a){a=[gc(a),pb("Width"),pb("Height")];return ra(a)}function oc(a){var b=[],c=a.q.D("_chartbeat4");c&&(t(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.q.remove("_chartbeat4"));return b}
function ic(a){a=a.q.D("_cb_svref",h)||gc(a)||"null";a==="null"&&(a="");return a}function hc(a){a=a.match(/^https?:\/\/([^\/]*)/);return!a?i:a[1]}function kc(){var a=r.performance&&r.performance.timing;if(!a||a.navigationStart==0)return-1;var b=a.navigationStart,a=a.loadEventStart;return Ja(b)&&b?Ja(a)&&a>b?a-b:u()-b:-1}q.terminate=function(){this.la.terminate();wb(y,this.gd);this.xb!==d&&Ia(r,"load",this.xb);Za(this.qb);L().d=d;L().n=d};
q.ya=function(){this.terminate();Ia(r,"unload",this.bc);this.bc=this.xb=this.q=this.Ka=this.k=i;this.la.ya();this.la=i;dc.ia.ya.call(this)};function pc(a){for(var b=J("m")||[];b.length;)a(b.shift());a={push:a};L().m=a};function qc(a){var b=a.offsetLeft,c=a.offsetTop,e=rc(a);b+=e.x;c+=e.y;for(var f=j,e=a.offsetParent;a&&a!==d&&a!==document.body;){if(a===e)e=rc(a),b+=a.offsetLeft+e.x,c+=a.offsetTop+e.y,e=a.offsetParent;if(sc(a,["position"]).position==="fixed"){f=h;break}a=a.parentElement}f&&(b+=0,c+=0);return{x:b,y:c}}
function sc(a,b){var c={},e,f;r.getComputedStyle?e=r.getComputedStyle(a,i):a.currentStyle?f="currentStyle":a.style&&(f="style");t(b,function(b){c[b]=e?e[b]||e.getPropertyValue(b):a[f][b]});return c}var tc=/matrix(3d)?\((.*)\)/;function rc(a){var b={x:0,y:0},a=sc(a,["transform"]).transform;if(!Ka(a))return b;var c=a.match(tc);if(!c)return b;var a=c[2].split(", "),e;w(c[1])?(c=12,e=13):(c=4,e=5);b.x=parseInt(a[c],10);b.y=parseInt(a[e],10);return b};function uc(){var a=r.location.href,a=a.replace(/-{2,}/g,"-"),a=jb(a);a.pathname=I(a.pathname);return a}
function vc(a){var b=G.D("_chartbeat6");if(!b)return i;var b=b.split("::"),c,e;if(b.length===1)c=b[0].split(","),e=0;else{var f,g=uc(),l=kb(g);t(b,function(a,b){var g=a.split(","),n=Ta(l,decodeURIComponent(g[0]));if(n===0)return c=g,e=b,j;if(f===d||n<f)f=n,c=g,e=b})}b.splice(e,1);a="_chartbeat6="+b.join("::")+wc(a);document.cookie=a;var a=[],b=decodeURIComponent(c[0]),g=decodeURIComponent(c[1]),o=c[2];c.splice(0,3);for(var n=c.length/3,C=0;C<n;C++){var E=C*3+2;a.push({De:b,origin:g,Oa:o,Ta:E<c.length?
c[E]:"",td:c[C*3],ve:c[C*3+1]})}return a}function wc(a){var b="",c;if(!Pa(a))return b;a.Ic&&(c=new Date,c.setTime(c.getTime()+a.Ic),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function xc(a){var b=a.topStorageDomain,a=a[B],c=r.location.hostname;return b?b:yc(c,a)?a:c.replace(/^www\./,"")}
function yc(a,b){if(a===b)return h;for(var c=b.split("."),e=a.split(".");c.length;){if(e.length===0)return j;if(c.pop()!==e.pop())return j}return h}function zc(a,b,c,e,f){this.vd=a;this.ud=b;this.we=c;this.Oa=e;this.Ta=f}function Ac(a){var b=a.d,c=i;if(b!==i){var e={};b.s&&t(b.s,function(a,b){e[b]=typeof a==="string"?{uc:a,Ta:""}:{uc:a.chosenVariant,Ta:a.specificLocation}});c={Tc:e,Oa:b.g,Hc:b.m}}return{status:a.s,data:c,code:a.c,message:a.m}};function Bc(a,b){for(var c=b||document.documentElement,e=[],f=i,g=a,l,o,n,C,E,Q;g&&g!==c;){l=g.nodeName.toLowerCase();f=g;o=f.nodeName;if((g=g.parentNode)&&g!==document.documentElement){n=g.children;C=0;for(E=0,Q=n.length;E<Q;E++){if(f===n[E]){l+="["+(1+E-C)+"]";break}n[E].nodeName!==o&&C++}}e.unshift(l)}return e.join("/")};function Cc(){this.Xc="_t_";this.xc=this.Vc=Xa;dc.call(this)}ea(Cc,dc);q=Cc.prototype;
q.N=function(){Cc.ia.N.call(this);Qb(this.k);var a=!!this.k[Lb],b=Yb(!!this.k[Mb]&&a);F(this.k,"mabServer","mabping.chartbeat.net");F(this.k,Nb,document.title);F(this.k,B,b);this.k[A]=this.k[A]?I(this.k[A]):Wb(a);this.ka=x(b);this.k[B]=x(this.k[B]);this.te=xc(this.k);this.Za=this.sb=j;this.Ac=[];var c=this,a=vc({domain:"."+this.te,Ic:6E4,path:"/"});if(a!==i)this.sb=h,t(a,function(a){c.Ac.push(new zc(a.origin,a.td,a.ve,a.Oa,a.Ta))});this.Jc=0;this.Cb=i;pc(v(this.Fd,this))};
q.Sa=function(){var a=this.la.Xa,b=Dc(this),c,e=this;this.sb&&t(this.Ac,function(f){c=b+"&x="+f.ud+"&v="+f.we+"&ml="+f.Oa+"&xo="+f.vd+"&e="+a+"&sl="+f.Ta;e.hb(c)});!this.Za&&this.Cb&&Ec(this,this.Cb);this.Za=h};q.Ab=function(){this.gb=kc();z.N();if(this.sb)this.qb=bb(v(this.na,this),500);this.na()};q.na=function(){var a,b;this.Za?(a=this.la.Xa,b=this.Jc*15,a-b>=15&&(this.Sa(),this.Jc+=1),a>=45&&this.terminate()):this.Sa()};
function Dc(a){var b=a.k;return Oa()+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b[B])+"&p="+encodeURIComponent(b[A])+"&d="+encodeURIComponent(a.ka)+"&u="+a.jb+"&c="+Math.round((u()-a.Ua)/600)/100}q.fb=k();q.re=function(a){a=Ac(a);this.Za?Ec(this,a):this.Cb=a};
function Ec(a,b){var c=Dc(a),e=b.status,f=b.data;if(e=="s"&&f!==i){var g=v(a.hb,a);Pa(f.Tc)&&t(f.Tc,function(a,b){g(c+"&x="+b+"&v="+a.uc+"&ml="+f.Oa+"&sl="+a.Ta+"&e=-1")});Object.prototype.toString.call(f.Hc)==="[object Array]"&&t(f.Hc,function(a){g(c+"&me=3&ml="+f.Oa+"&x="+a)})}else e=="e"&&a.hb(c+"&me="+b.code)}
q.Fd=function(a,b){for(var c=0,e=arguments.length;c<e;c++){var a=arguments[c],f=a.shift();f==="t"?this.re.apply(this,a):f==="v"?this.Sc.apply(this,a):f==="sv"?this.ne.apply(this,a):f==="ev"&&this.Sc.apply(this,a)}};q.pb=function(){this.xc();Cc.ia.pb.call(this)};q.Bb=function(){L().m=[];this.Vc();Cc.ia.Bb.call(this)};q.ne=function(a){this.Vc=a};q.Sc=function(a){this.xc=a};q.terminate=function(){this.Ee=d;this.Cb=i;this.Za=this.sb=d;Cc.ia.terminate.call(this)};if(!G.D("cb_optout")&&!r.pSUPERFLY_mab){var Fc=new Cc,Gc={};Gc.evps=v(Fc.pb,Fc);Gc.svps=v(Fc.Bb,Fc);r.pSUPERFLY_mab=Gc;jc(Fc)};var Hc,Ic,Jc;
function Kc(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16);Lc();if(b!=="NONE")b=b.indexOf("HUD2.")===0?b.substr(5):"OLD",a="https://static.chartbeat.com/js/inpage.js",b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=w(d)?d:{},b.src=a,a=tb("script",b),a.setAttribute("type","text/javascript"),b=document.head||document.getElementsByTagName("head")[0],w(d)?d.appendChild(a):b&&b.appendChild(a)}}
function Lc(){ab(Ic);Ic=d;Ia(r,"message",Kc);Jc&&Jc.parentNode&&Jc.parentNode.removeChild(Jc);Jc=d};function Mc(){var a=r._sf_async_config&&r._sf_async_config.domain;if(a&&!Hc){Hc=h;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);Ha(r,"message",Kc);Ic=$a(Lc,1E4);var b=w(d)?d:{};b.src=a;a=tb("iframe",b);a.style.display="none";w(d)?d.appendChild(a):document.body&&document.body.appendChild(a);Jc=a}}
function Nc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=H.Y(h),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Mc(),Ia(r,"message",Nc))}};function Oc(a,b){this.bd=b;this.$c=a[Lb];this.Zc=a[Mb];this.za=a[A];this.Ga=a[Nb];this.vc=a[B];this.xe=a[Ob];this.tc=(this.pa=Xb())?this.pa.hostname:"";this.kb=this.pa?I(this.pa.pathname)+this.pa.search+this.pa.hash:"";this.Rc=Wb(j);this.je=Yb(j);var c=lb("property","meta",i,"og:url");this.eb=(this.Qa=c&&c.length?jb(c[0].content):i)?I(this.Qa.pathname)+this.Qa.search+this.Qa.hash:"";this.Ld=this.Qa?this.Qa.hostname:"";this.Nb=document.title||"";var e;if((c=lb("property","meta",i,"og:title"))&&c.length)e=
c[0].content;this.vb=e;var f;if((e=lb("property","meta",i,"twitter:title"))&&e.length)f=e[0].content;this.ib=f;f=!!this.$c;e=this.$c!==d;var c=!!this.Zc,g=this.Zc!==d,l=!!this.pa,o;o=x(this.tc);var n=x(this.je);o=o===n;var n=!!this.eb,C=!this.pa?j:this.kb===this.eb,E=this.kb===this.Rc,Q;Q=this.kb;var T=Da(this.Rc);Q=Q===T;var T=!!this.Nb,fa=!!this.vb,aa=!!this.ib,K=this.Nb===this.vb,D=!this.ib?j:this.Nb===this.ib,ha=!this.vb||!this.ib?j:this.vb===this.ib,ia=!!this.Ga,pd=!!this.za,qd=this.za?this.za.charAt(0)!==
"/":j,rd=!this.pa?j:this.za===this.kb,sd=!this.eb?j:this.za===this.eb,td=!this.pa?j:this.vc===x(this.tc),ud=!this.eb?j:this.vc===x(this.Ld),vd=!!this.bd,wd=this.bd?j:!!this.xe,xd=Oa()==="https:",yd=!!XMLHttpRequest,ya;this.za?(ya=Ea(this.za),ya=ya!==Da(ya)):ya=j;f=[f,e,c,g,l,o,n,C,E,Q,T,fa,aa,K,D,ha,ia,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,ya];e=1;for(g=c=0;g<f.length;g++)c|=f[g]&&e,e<<=1;this.md=("00000000"+c.toString(16)).slice(-8)};function Pc(){"postMessage"in window&&Ha(r,"message",v(this.Cd,this));dc.call(this);Pb("_cbq",v(this.Qc,this))}ea(Pc,dc);
Pc.prototype.N=function(){Pc.ia.N.call(this);var a=this.jb;L().u=a;a=this.Ba;L().t=a;this.Kd=new Oc(this.k,this.Ub);this.Hb=i;Qb(this.k);var a=!!this.k[Lb],b=Yb(!!this.k[Mb]&&a);F(this.k,"pingServer","ping.chartbeat.net");F(this.k,Nb,document.title);F(this.k,B,b);this.k[A]=this.k[A]?I(this.k[A]):Wb(a);this.ka=x(b);this.k[B]=x(this.k[B]);this.jd=vb(y,"c",this.Qd,this);this.kd=vb(y,"r",this.Rd,this);this.Ma=i};Pc.prototype.fd=function(a){this.Hb=a};
Pc.prototype.fb=function(){this.q.update("_chartbeat4",["t="+this.Ba,"E="+this.la.Xa,"x="+lc(this),"c="+Math.round((u()-this.Ua)/600)/100,"y="+pb("Height"),"w="+ob()].join("&"),60,d,d,1)};var ib="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,_x,_y,_z,_s,t,V,z,i,L,tz,l,,sn,C,sv,sr,sd,im".split(",");q=Pc.prototype;
q.Sa=function(a){this.Nc++;var b={};b.g=this.k.uid;b.g0=Rb(this.k,"sections");b.g1=Rb(this.k,"authors");b.g2=Rb(this.k,"zone");b.g3=Rb(this.k,"sponsorName");b.g4=Rb(this.k,"type");!this.k.noCookies&&this.q.isSupported()?b.n=this.Xb:b.nc=1;b.c=Math.round((u()-this.Ua)/600)/100;b.E=this.la.Xa;var c=lc(this);this.cb=Math.max(this.cb,c);b.x=c;b.m=this.cb;b.y=pb("Height");b.o=pb("Width");b.w=ob();b.b=this.gb>0?this.gb:"";if(this.Cc)b.f=this.Cc;b[""]=Sb(this.k);b.t=this.Ba;b.V=106;b.tz=(new Date).getTimezoneOffset();
b.sn=this.Nc;b.sv=this.qe;b.sr=this.pe;b.sd=this.oe;c=this.la.ab;b.h=encodeURIComponent(this.k[B]);b.p=encodeURIComponent(this.k[A]);b.u=this.jb;b.d=encodeURIComponent(this.ka);b.j=Math.round((this.Na+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;z.hd()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=fc(this);if(this.gc){this.gc=j;if(c)this.Ma=Qc(this);b.i=nc(this);var e=this.k.hudTrackable;e!==d&&(b.L=e?"1":"0");this.k.alias&&(b.PA=encodeURIComponent(this.k.alias))}if(c){if(this.Ma){if(b.v=
encodeURIComponent(this.Ma.path),b.K=Rc(this.Ma),this.Ma.Yb>1)b.l1=this.Ma.Yb}else b.v=gc(this);this.Ub&&(b.vp=1)}else b.r=gc(this);c=cb(b.v);L().v=c;c=cb(b.r);L().r=c;b.A=this.Hb?this.Hb:"";b._c=fb("utm_campaign",this.k.campaignTag);b._m=fb("utm_medium",this.k.mediumTag);b._x=fb("utm_source",this.k.sourceTag);b._y=fb("utm_content",this.k.contentTag);b._z=fb("utm_term",this.k.termTag);b.im=this.Kd.md;this.k.idSync?(c=[],ja(new ga,this.k.idSync,c),c=encodeURIComponent(c.join(""))):c="";b._s=c;b.z=
oc(this);b.C=this.k.mobileApp?1:"";b.KK=a?Rc(a):"";b.l=Vb(this.q)?1:"";this.la.ab=0;this.hb(Oa()+"//"+this.k.pingServer+"/ping?"+hb(b))};
q.Cd=function(a){var b=this.k,c=b.playerdomain||this.ka;if(ta(a.origin)===ta(c))if(c=a.data,Ka(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.Qc(a));else if(c=="cbdata?"){var c="&u="+J("u"),e="&t="+J("t"),f="&v="+J("v"),g="&r="+J("r"),b="domain="+encodeURIComponent(b[B])+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b[A])+"&title="+nc(this)+"&referrer="+gc(this)+"&internal="+(fc(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.ka)+
c+e+f+g+"&utoken="+this.jb;a.source.postMessage(b,"*")}};q.Qc=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.Na=0};function Sc(a){a=a.replace(/-{2,}/g,"-");a=jb(a);a.pathname=I(a.pathname);return a}q.Qd=function(a){Tc(this,a,"c")};q.Rd=function(a){Tc(this,a,"r")};
function Tc(a,b,c){if(a.ic&&u()-a.Ua>=a.tb)a.terminate();else{var e=b.href||"",e=Sc(e);if(e.protocol.indexOf("http")===0){var f=e.hostname!==r.location.hostname,e=kb(e),g=qb(b,function(a){return a.id}),l=Bc(b,g),o="";a.k.moduleAttribute&&(o=(o=mb(b,a.k.moduleAttribute))?o.getAttribute(a.k.moduleAttribute):"",o=o.replace(/::/g,"-").substr(0,40));g?(l&&(l="/"+l),l="*[@id='"+g.id+"']"+l,g=Bc(b)):g=l;l=pa(l);g=pa(g);b=qc(b);c={left:b.x,top:b.y,path:a.k[A],href:e,qc:l,Gb:g,pc:"",jc:c,Yb:0,xd:a.k[B],Wb:o};
a.Sa(c);f||a.q.update("_chartbeat5",Uc(c),60,j,d,3,function(a){a=a.split(",");return a[2]+","+a[3]})}}}function Rc(a){return[a.left,a.top,a.qc,encodeURIComponent(a.pc),a.jc,encodeURIComponent(a.href),a.Gb,a.Wb].join("::")}function Uc(a){var b=encodeURIComponent(a.pc),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.qc,b,a.jc,a.Gb,encodeURIComponent(a.xd),a.Wb].join(",")}
function Qc(a){var b=a.q.D("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,e,f=i,g,l=Sc(r.location.href),o=kb(l);t(c,function(a,b){var c=a.split(","),l=decodeURIComponent(c[3]);if(l){l=Ga(o,l);if(l===0)return e=c,f=b,j;else if(l===i)return h;if(g===d||l<g)g=l,e=c,f=b}});if(f===i)return i;c.splice(f,1);a.q.create("_chartbeat5",c.join("::"),60);(a=e[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:e[0],top:e[1],path:decodeURIComponent(e[2]),href:decodeURIComponent(e[3]),
qc:e[4]||"",pc:"",Gb:e.length>7?e[7]:"",jc:e.length>6?e[6]:"c",Yb:b,Wb:e[9]?e[9]:""}}q.terminate=function(){wb(y,this.jd);wb(y,this.kd);Pc.ia.terminate.call(this)};var N="ct",O="s1";function P(a){this.a=a;this.F=this.G=j;this.B=u();this.ha()}q=P.prototype;q.ha=function(){this.a.currentTime()>0&&!this.a.paused&&!this.a.ended&&this.fa();this.a.on("play",v(this.fa,this));this.a.on("dispose",v(this.Td,this));this.a.ready(v(this.oa,this))};q.oa=function(){this.G=h};q.fa=function(){this.F=h};q.Td=function(){var a=r._cbv;a&&a.push&&a.push(["removePlayer",this.a])};q.O=function(){return this.G&&this.M()!==""};
q.Pb=function(){var a;this.a.cb_configs&&this.a.cb_configs[B]?a=this.a.cb_configs[B]:!a&&r._sf_async_config&&r._sf_async_config[B]&&(a=r._sf_async_config[B]);return a};q.Qb=function(){var a;this.a.cb_configs&&this.a.cb_configs.uid?a=this.a.cb_configs.uid:!a&&r._sf_async_config&&r._sf_async_config.uid&&(a=r._sf_async_config.uid);return a};q.M=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("name")?a.name:this.a.el().getAttribute("title"))||""};
q.J=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("id")?a.id:this.a.el().attributes["data-video-id"]&&this.a.el().attributes["data-video-id"].value?this.a.el().attributes["data-video-id"].value:this.a.src())||""};q.U=function(){return N};q.P=p("");q.ca=function(){var a=this.a.duration();return Va(a)};q.H=function(){return!this.F?O:this.a.ended()?"s4":this.a.paused()?"s3":"s2"};q.X=function(){var a=this.a.currentTime();return Va(a)};q.T=p(-1);
q.ba=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("thumbnail")?a.thumbnail:this.a.poster())||""};q.Z=k();q.S=k();q.da=function(){return Ua(this.B)};q.$=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.sections?a=this.a.cb_configs.sections.split(","):a.length==0&&r._sf_async_config&&r._sf_async_config.sections&&(a=r._sf_async_config.sections.split(","));if(a.length>0&&a[0]!=="")return a};
q.Q=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.authors?a=this.a.cb_configs.authors.split(","):a.length==0&&r._sf_async_config&&r._sf_async_config.authors&&(a=r._sf_async_config.authors.split(","));if(a.length>0&&a[0]!=="")return a};q.aa=p("BCN");P.prototype.getStrategyName=P.prototype.aa;P.prototype.isReady=P.prototype.O;P.prototype.getHost=P.prototype.Pb;P.prototype.getUid=P.prototype.Qb;P.prototype.getTitle=P.prototype.M;P.prototype.getVideoPath=P.prototype.J;
P.prototype.getContentType=P.prototype.U;P.prototype.getAdPosition=P.prototype.P;P.prototype.getTotalDuration=P.prototype.ca;P.prototype.getState=P.prototype.H;P.prototype.getCurrentPlayTime=P.prototype.X;P.prototype.getBitrate=P.prototype.T;P.prototype.getThumbnailPath=P.prototype.ba;P.prototype.getPlayerType=P.prototype.Z;P.prototype.getAutoplayType=P.prototype.S;P.prototype.getViewStartTime=P.prototype.da;P.prototype.getSections=P.prototype.$;P.prototype.getAuthors=P.prototype.Q;
P.verify=function(a){return a.controlBar!==d};function R(a){this.Ya=this.ka=d;this.G=j;this.Pc=this.wc=-1;this.ta=i;this.a=a;this.F=j;this.cc=h;this.B=u();this.dc="";for(var a=window.experienceJSON.data.configuredProperties.plugins.list.split(" "),b=a.length,c=0;c<b;c++){var e=a[c];if((e.indexOf("chartbeat")>=0||e.indexOf("localhost")>=0)&&e.indexOf(".js")>=0){this.dc=e;break}}if(this.dc){a=eb(this.dc);if(this.ka=a[B])this.ka=this.ka.replace(/^video@/,"");this.Ya=a.uid}a=window.brightcove;this.a=a.api.getExperience();b=this.a.getModule(a.api.modules.APIModules.EXPERIENCE);
b.getReady()?this.Mc():b.addEventListener(a.player.events.ExperienceEvent.TEMPLATE_READY,s(this.Mc,this))}q=R.prototype;
q.Mc=function(){var a=window.brightcove,b=this.a.getModule(a.api.modules.APIModules.VIDEO_PLAYER),c=this;b.getVideoDuration(function(a){c.wc=Math.round(a)});b.getCurrentVideo(function(a){c.ta=a});a=a.api.events.MediaEvent;b.addEventListener(a.PROGRESS,s(this.ae,this));b.addEventListener(a.STOP,s(this.ce,this));b.addEventListener(a.COMPLETE,s(this.Sd,this));b.addEventListener(a.BEGIN,s(this.fa,this));this.G=h};q.ae=function(a){this.Pc=a.position;this.va=this.cc=j};q.ce=function(){this.cc=h};
q.Sd=function(){this.va=h};q.fa=function(){this.va=j;if(!this.F)this.F=h};q.O=m("G");q.M=function(){var a="";this.ta&&(a=this.ta.displayName);return a};q.J=function(){var a="";this.ta&&(a="video@"+this.ka+"/"+this.ta.id);return a};q.U=function(){return N};q.P=p("");q.ca=m("wc");q.H=function(){return!this.F?O:this.va?"s4":this.cc?"s3":"s2"};q.X=function(){return Va(this.Pc)};q.T=p(-1);q.ba=function(){var a="";this.ta&&(a=this.ta.thumbnailURL);return a};q.Z=k();
q.da=function(){return isNaN(this.B)?0:Sa(this.B)};q.Q=k();q.$=function(){var a;this.ta&&(a=this.ta.tags);return a};q.S=p("unkn");q.aa=p("BC");q.Pb=m("ka");q.Qb=m("Ya");R.prototype.isReady=R.prototype.O;R.prototype.getTitle=R.prototype.M;R.prototype.getVideoPath=R.prototype.J;R.prototype.getContentType=R.prototype.U;R.prototype.getAdPosition=R.prototype.P;R.prototype.getTotalDuration=R.prototype.ca;R.prototype.getState=R.prototype.H;R.prototype.getCurrentPlayTime=R.prototype.X;
R.prototype.getBitrate=R.prototype.T;R.prototype.getThumbnailPath=R.prototype.ba;R.prototype.getPlayerType=R.prototype.Z;R.prototype.getViewStartTime=R.prototype.da;R.prototype.getAuthors=R.prototype.Q;R.prototype.getSections=R.prototype.$;R.prototype.getAutoplayType=R.prototype.S;R.verify=function(a){return a===window.brightcove};R.prototype.getStrategyName=R.prototype.aa;R.prototype.getHost=R.prototype.Pb;R.prototype.getUid=R.prototype.Qb;function S(a){this.a=a;this.F=this.G=j;this.B=u();this.Gc=this.ua=this.Aa=d;this.Ga=this.Fa="";this.Vb=d;this.ha()}var Vc=/url\(['"]?([^'"\)]*)['"]?\)/;q=S.prototype;
q.Ob=function(){var a=this.Gc=this.J();if(this.a.conf&&(this.Ga=this.a.conf.title?this.a.conf.title:"",this.Fa=this.a.conf.poster?this.a.conf.poster:"",this.Ga&&this.Fa))return h;var b=lb("name","param"),c=d;t(b,function(b){if(b.attributes.name&&b.attributes.name.value==="flashvars"&&b.value.indexOf(a)!==-1)return c=b,j});c===d&&(b=lb("src","video"),t(b,function(b){if(b.attributes.src.value&&a.indexOf(b.attributes.src.value)!=-1)return c=b,j}));b=mb(c,"data-swf")||mb(c,"poster");if(b===j)return j;
this.Fa=b.attributes.poster&&b.attributes.poster.value;if(!this.Fa){var e=b.style.background;if(e&&(e=e.match(Vc)))this.Fa=e[1]}this.Ga=b.title;if(this.Vb!==d)clearInterval(this.Vb),this.G=h;return h};function Wc(a){if(a.Gc!==a.J())a.Fa="",a.Ga="",a.Ob()}q.ha=function(){this.a.ready?this.oa():this.a.bind("ready",s(this.oa,this));this.a.bind("resume",s(this.fa,this));this.a.playing&&this.fa()};q.oa=function(){this.Ob()===j?this.Vb=setInterval(s(this.Ob,this),1E3):this.G=h};
q.fa=function(){if(!this.F)this.F=h};q.O=m("G");q.M=function(){Wc(this);return this.Ga};q.J=function(){return this.a.video.url||this.a.video.src};q.U=function(){return N};q.P=p("");q.ca=function(){return this.a.video.duration&&this.a.video.duration*1E3};q.H=function(){return!this.F?O:this.a.Fe?"s4":this.a.paused?"s3":"s2"};q.X=function(){return Va(this.a.video.time)};q.T=p(-1);q.ba=function(){Wc(this);return this.Fa};q.Z=k();q.S=k();q.da=function(){return isNaN(this.B)?0:Sa(this.B)};q.$=m("Aa");
q.Q=m("ua");q.aa=p("FP");S.prototype.getStrategyName=S.prototype.aa;S.prototype.isReady=S.prototype.O;S.prototype.getTitle=S.prototype.M;S.prototype.getVideoPath=S.prototype.J;S.prototype.getContentType=S.prototype.U;S.prototype.getAdPosition=S.prototype.P;S.prototype.getTotalDuration=S.prototype.ca;S.prototype.getState=S.prototype.H;S.prototype.getCurrentPlayTime=S.prototype.X;S.prototype.getBitrate=S.prototype.T;S.prototype.getThumbnailPath=S.prototype.ba;S.prototype.getPlayerType=S.prototype.Z;
S.prototype.getAutoplayType=S.prototype.S;S.prototype.getViewStartTime=S.prototype.da;S.prototype.getSections=S.prototype.$;S.prototype.getAuthors=S.prototype.Q;S.verify=function(a){return window.flowplayer&&a.engine&&a.engine.engineName};function U(a){this.a=a;this.Fb=this.F=this.G=j;this.B=u();this.ua=this.Aa=d;this.ha()}q=U.prototype;q.ha=function(){this.a.readyState>0&&this.oa();this.a.currentTime>0&&!this.a.paused&&!this.a.ended&&this.fa();this.a.addEventListener("canplay",v(this.oa,this));var a=v(this.fa,this);this.a.addEventListener("playing",a);this.a.addEventListener("webkitbeginfullscreen",a);this.a.addEventListener("webkitendfullscreen",v(this.ie,this))};q.oa=function(){this.G=h};q.fa=function(){this.F=h;this.Fb=j};
q.ie=function(){this.Fb=h};q.O=m("G");q.M=function(){return this.a.attributes.title&&this.a.attributes.title.value||""};q.J=function(){return this.a.currentSrc||""};q.U=function(){return N};q.P=p("");q.ca=function(){return Va(this.a.duration)};q.H=function(){return!this.F?O:this.a.ended||this.Fb&&this.a.currentTime==this.a.duration?"s4":this.a.paused||this.Fb?"s3":"s2"};q.X=function(){return Va(this.a.currentTime)};q.T=p(-1);q.ba=function(){return this.a.poster||""};q.Z=k();
q.S=function(){return this.a.autoplay?"auto":"man"};q.da=function(){return Ua(this.B)};q.$=m("Aa");q.Q=m("ua");q.aa=p("H5");U.prototype.getStrategyName=U.prototype.aa;U.prototype.isReady=U.prototype.O;U.prototype.getTitle=U.prototype.M;U.prototype.getVideoPath=U.prototype.J;U.prototype.getContentType=U.prototype.U;U.prototype.getAdPosition=U.prototype.P;U.prototype.getTotalDuration=U.prototype.ca;U.prototype.getState=U.prototype.H;U.prototype.getCurrentPlayTime=U.prototype.X;
U.prototype.getBitrate=U.prototype.T;U.prototype.getThumbnailPath=U.prototype.ba;U.prototype.getPlayerType=U.prototype.Z;U.prototype.getAutoplayType=U.prototype.S;U.prototype.getViewStartTime=U.prototype.da;U.prototype.getSections=U.prototype.$;U.prototype.getAuthors=U.prototype.Q;U.verify=function(a){var b=a instanceof HTMLElement&&a.nodeName==="VIDEO",a=a.getAttribute&&a.getAttribute("data-account")!==i;return b&&!a};function V(a){this.a=a;this.F=this.va=this.G=j;this.B=u();this.bb=j;this.ha()}q=V.prototype;q.ha=function(){function a(a,f){f=s(f,c);if(ba(b.on)=="function")b.on(a,f);else{var g="on"+a.substr(0,1).toUpperCase()+a.substr(1);if(ba(b[g])=="function")b[g](f)}}var b=this.a,c=this;a("ready",this.oa);a("time",this.ee);a("complete",this.fe);a("adStarted",this.Pa);a("adPlay",this.Pa);a("adImpression",this.Pa);a("adTime",this.Pa);a("adComplete",this.Zb);a("adSkipped",this.Zb);a("adError",this.Zb)};
q.oa=function(){this.G=h};q.ee=function(){this.va=j;this.F=h;this.bb=j};q.fe=function(){this.va=h};q.Pa=function(){this.bb=this.F=h};q.Zb=function(){this.bb=j};q.O=function(){this.a.getState();return this.G||this.a.getState()!==d};q.M=function(){var a=Xc(this);return!a?"":a.title};function Xc(a){if(a.a.getPlaylistIndex===d)return a.a.getPlaylistItem();var b=a.a.getPlaylist();if(!b)return i;var c=b.length,a=a.a.getPlaylistIndex();return c===0||c<=a?i:b[a]}
q.J=function(){var a=Xc(this);return!a?"":a.mediaid||a.file};q.U=function(){return this.bb?"ad":N};q.P=p("");q.ca=function(){var a=this.a.getDuration();if(a>0)return Math.round(a*1E3)};q.H=function(){if(!this.F)return O;if(this.bb)return"s2";if(this.va)return"s4";var a=this.a.getState();return a&&a.toUpperCase()==="PAUSED"?"s3":"s2"};q.X=function(){var a=this.a.getPosition();return Va(a)};q.T=p(-1);q.ba=function(){var a=Xc(this);return!a?"":a.image};q.Z=k();
q.da=function(){return isNaN(this.B)?0:Sa(this.B)};q.Q=k();q.$=k();q.S=p("unkn");q.aa=p("JW");V.prototype.getStrategyName=V.prototype.aa;V.prototype.isReady=V.prototype.O;V.prototype.getTitle=V.prototype.M;V.prototype.getVideoPath=V.prototype.J;V.prototype.getContentType=V.prototype.U;V.prototype.getAdPosition=V.prototype.P;V.prototype.getTotalDuration=V.prototype.ca;V.prototype.getState=V.prototype.H;V.prototype.getCurrentPlayTime=V.prototype.X;V.prototype.getBitrate=V.prototype.T;
V.prototype.getThumbnailPath=V.prototype.ba;V.prototype.getPlayerType=V.prototype.Z;V.prototype.getViewStartTime=V.prototype.da;V.prototype.getAuthors=V.prototype.Q;V.prototype.getSections=V.prototype.$;V.prototype.getAutoplayType=V.prototype.S;V.verify=function(a){return w(a.id)&&w(a.registerPlugin)};function W(a){this.a=a;this.ad="";this.ja=O;this.wa=N;this.ra="";this.B=u();this.ha()}q=W.prototype;q.ha=function(){this.a.kBind("playerStateChange.cb",s(this.he,this));this.a.kBind("playerUpdatePlayhead.cb",s(this.$d,this));this.a.kBind("playerPlayEnd.cb",s(this.ge,this));this.a.kBind("adStart.cb",s(this.Pa,this));this.a.kBind("adEnd.cb",s(this.Nd,this));this.a.kBind("switchingChangeComplete.cb",s(this.de,this))};
q.he=function(a){switch(a){case "playing":this.ja="s2";break;case "buffering":this.ja="s3";break;case "paused":this.ja="s3"}};q.$d=function(){this.ja="s2";this.a.kUnbind("playerUpdatePlayhead.cb")};q.ge=function(){this.ja="s4"};q.Pa=function(a){this.wa="ad";switch(a){case "pre":this.ra="a1";break;case "post":this.ra="a3";break;case "mid":this.ra="a2";break;case "main":this.ra="a5"}};q.Nd=function(){this.wa=N};q.de=function(a,b){this.nd=b};
q.O=function(){return this.a.evaluate("{mediaProxy.entry.name}")!=i};q.M=function(){return this.a.evaluate("{mediaProxy.entry.name}")};q.J=function(){if(!this.O())return this.ad;var a=this.a.evaluate("{mediaProxy.entry.id}");return(this.ad=a)||""};q.U=m("wa");q.P=m("ra");q.ca=function(){var a=this.a.evaluate("{duration}");return Va(a)};q.H=m("ja");q.X=function(){var a=this.a.evaluate("{video.player.currentTime}");return Va(a)};q.T=m("nd");
q.ba=function(){return this.a.evaluate("{mediaProxy.entry.thumbnailUrl}")||""};q.Z=k();q.S=function(){var a=this.a.evaluate("{configProxy.flashvars.autoPlay}"),b=this.a.evaluate("{configProxy.flashvars.playlistAPI.autoContinue}"),c=this.a.evaluate("{playlistAPI.dataProvider.selectedIndex}");return b&&c>0?"cont":a?"auto":"man"};q.da=function(){return isNaN(this.B)?0:Ua(this.B)};q.$=function(){var a=this.a.evaluate("{mediaProxy.entry.tags}");if(a)return a.split(",")};
q.Q=function(){var a=this.a.evaluate("{mediaProxy.entry.creatorId}");if(a)return[encodeURIComponent(a)]};q.aa=p("KT");W.prototype.getStrategyName=W.prototype.aa;W.prototype.isReady=W.prototype.O;W.prototype.getTitle=W.prototype.M;W.prototype.getVideoPath=W.prototype.J;W.prototype.getContentType=W.prototype.U;W.prototype.getAdPosition=W.prototype.P;W.prototype.getTotalDuration=W.prototype.ca;W.prototype.getState=W.prototype.H;W.prototype.getCurrentPlayTime=W.prototype.X;W.prototype.getBitrate=W.prototype.T;
W.prototype.getThumbnailPath=W.prototype.ba;W.prototype.getPlayerType=W.prototype.Z;W.prototype.getAutoplayType=W.prototype.S;W.prototype.getViewStartTime=W.prototype.da;W.prototype.getSections=W.prototype.$;W.prototype.getAuthors=W.prototype.Q;W.verify=function(a){return typeof a.kBind=="function"};function X(a){this.sc=d;this.a=a;this.Fc=d;this.G=j;this.Ia=d;this.F=j;this.ua=this.Aa=this.B=d;this.sc=r.OO;this.Fc=this.a.mb;this.B=u();this.ha()}q=X.prototype;
q.ha=function(){var a=this.Fc,b=this.sc.EVENTS;a.subscribe(b.CONTENT_TREE_FETCHED,"OoyalaStrategyPlugin",s(this.oa,this));a.subscribe(b.WILL_PLAY_ADS,"OoyalaStrategyPlugin",s(this.Pd,this));a.subscribe(b.PLAYING,"OoyalaStrategyPlugin",s(this.fa,this));a.subscribe(b.ADS_PLAYED,"OoyalaStrategyPlugin",s(this.Od,this));a.subscribe(b.METADATA_FETCHED,"OoyalaStrategyPlugin",s(this.Zd,this));a.subscribe(b.EMBED_CODE_CHANGED,"OoyalaStrategyPlugin",s(this.Ud,this))};q.oa=function(){this.G=h};
q.Pd=function(){var a=this.a.getPlayheadTime(),b=this.a.getDuration();isNaN(a)&&(a=0);this.Ia=a===0?"a1":Yc(a,b)?"a3":"a2"};q.fa=function(){this.F=h};q.Od=function(){this.Ia=d};q.Zd=k();q.O=function(){var a=this.a.getState();if(a==="ready"||a==="playing"||a==="paused")this.G=h;return this.G};q.M=function(){var a=this.a.getItem();return a?a.title:""};
q.J=function(){var a=this.a.getEmbedCode&&this.a.getEmbedCode();if(a)return a;a=this.a.getItem()||{};return a.embed_code||a.embedCode||this.a.embedCode||""};q.U=function(){return this.Ia===d?N:"ad"};q.P=function(){return this.Ia?this.Ia:""};q.ca=function(){var a=this.a.getItem(),a=a&&a.duration||this.a.getDuration()*1E3;return a===-1||!isFinite(a)?-1:a};
q.H=function(){if(!this.F)return O;if(this.a.getState()==="paused")return"s3";var a=this.a.getPlayheadTime(),b=this.a.getDuration();return Yc(a,b)?"s4":"s2"};function Yc(a,b){return a===b||Math.floor(a)===Math.floor(b)||Math.ceil(a)===Math.ceil(b)||Math.ceil(a)===Math.floor(b)||Math.floor(a)===Math.ceil(b)}q.Ud=function(){this.Ia=d};q.X=function(){var a=this.a.getPlayheadTime();return a===-1||isNaN(a)?-1:a*1E3};
q.T=function(){var a=this.a.getCurrentBitrate&&this.a.getCurrentBitrate();return a?a.bitrate:0};q.ba=function(){var a=this.a.getItem();return!a?"":a.promo||a.promo_image||a.thumbnail_image};q.Z=k();q.S=k();q.da=function(){return isNaN(this.B)?0:Ua(this.B||0)};q.$=m("Aa");q.Q=m("ua");q.aa=p("OO");X.prototype.getStrategyName=X.prototype.aa;X.prototype.isReady=X.prototype.O;X.prototype.getTitle=X.prototype.M;X.prototype.getVideoPath=X.prototype.J;X.prototype.getContentType=X.prototype.U;
X.prototype.getAdPosition=X.prototype.P;X.prototype.getTotalDuration=X.prototype.ca;X.prototype.getState=X.prototype.H;X.prototype.getCurrentPlayTime=X.prototype.X;X.prototype.getBitrate=X.prototype.T;X.prototype.getThumbnailPath=X.prototype.ba;X.prototype.getPlayerType=X.prototype.Z;X.prototype.getAutoplayType=X.prototype.S;X.prototype.getViewStartTime=X.prototype.da;X.prototype.getSections=X.prototype.$;X.prototype.getAuthors=X.prototype.Q;
X.verify=function(a){return a.hasOwnProperty("mb")&&a.hasOwnProperty("subscribe")&&a.hasOwnProperty("modules")&&a.hasOwnProperty("isAdPlaying")};function Y(a){this.a=a;this.ga=i;this.$a="";this.ja=O;this.wa=N;this.ra="";this.B=u();this.a.controller.plugInLoaded&&this.a.controller.plugInLoaded(this)}q=Y.prototype;q.Id=function(a){this.ha(a.controller)};
q.ha=function(a){a.addEventListener("OnLoadRelease",v(this.Kc,this));a.addEventListener("OnLoadReleaseUrl",v(this.Kc,this));a.addEventListener("OnReleaseStart",v(this.be,this));a.addEventListener("OnMediaPlay",v(this.Wd,this));a.addEventListener("OnMediaStart",v(this.Yd,this));a.addEventListener("OnMediaPause",v(this.ac,this));a.addEventListener("OnMediaComplete",v(this.Vd,this));a.addEventListener("OnMediaError",v(this.ac,this));a.addEventListener("OnMediaBuffer",v(this.ac,this));a.addEventListener("OnMediaPlaying",
v(this.Xd,this))};q.Kc=function(a){if(a.data&&a.data.title)this.ga=a.data;if(a.data&&a.data.guid)this.$a=a.data.guid};q.be=function(a){t(a.data.clips,v(function(a){if(a=a.baseClip.guid)return this.$a=a,j},this));if(this.$a&&a.data.release&&a.data.release.title)this.ga=a.data.release};q.Wd=function(){this.ja="s2"};q.Yd=function(a){this.ja="s2";a=a.data.baseClip;a.isAd?(this.wa="ad",this.ra=a.isMid?"a2":"a1"):(this.wa=N,this.ra="")};q.ac=function(){if(this.ja!=O)this.ja="s3"};
q.Vd=function(){this.ja="s4"};q.Xd=function(a){this.rd=a.currentTime};q.O=function(){return this.ga!=i};q.M=function(){return this.ga.title};q.J=function(){return!this.$a?"":this.$a};q.U=m("wa");q.P=m("ra");q.ca=function(){return this.ga.duration};q.H=m("ja");q.X=m("rd");q.T=function(){return this.ga.bitrate};q.ba=function(){return this.ga&&this.ga.defaultThumbnailUrl?this.ga.defaultThumbnailUrl:this.ga.pid?"http://link.theplatform.com/s/ngc/"+this.ga.pid+"?format=poster&height=70&width=95":""};
q.Z=k();q.S=k();q.da=function(){return isNaN(this.B)?0:this.B===d?0:u()-this.B};q.$=function(){var a=this.ga.keywords?this.ga.keywords.split(","):[],b=[];t(this.ga.categories?this.ga.categories:[],function(a){b.push(encodeURIComponent(a.name))});t(a,function(a){b.push(encodeURIComponent(a.trim()))});return b};q.Q=k();q.aa=p("TP");Y.prototype.initialize=Y.prototype.Id;Y.prototype.getStrategyName=Y.prototype.aa;Y.prototype.isReady=Y.prototype.O;Y.prototype.getTitle=Y.prototype.M;
Y.prototype.getVideoPath=Y.prototype.J;Y.prototype.getContentType=Y.prototype.U;Y.prototype.getAdPosition=Y.prototype.P;Y.prototype.getTotalDuration=Y.prototype.ca;Y.prototype.getState=Y.prototype.H;Y.prototype.getCurrentPlayTime=Y.prototype.X;Y.prototype.getBitrate=Y.prototype.T;Y.prototype.getThumbnailPath=Y.prototype.ba;Y.prototype.getPlayerType=Y.prototype.Z;Y.prototype.getAutoplayType=Y.prototype.S;Y.prototype.getViewStartTime=Y.prototype.da;Y.prototype.getSections=Y.prototype.$;
Y.prototype.getAuthors=Y.prototype.Q;Y.verify=function(a){return typeof a.controller!=="undefined"};function Zc(a,b){this.a=a;this.Yc=b;this.La=window.location!=window.parent.location;this.Oc=j;this.se=u();this.Xc="_v_";this.sa={};dc.call(this)}ea(Zc,dc);var $c=r.QUICK_TEST?1E4:6E4,ad="autoDetect",bd={Be:"title",Ce:"videopath",Ae:"thumbnailpath"},cd={};q=Zc.prototype;
q.N=function(){this.Xb=(this.Ra=this.q.D("_chartbeat3"))?0:1;this.oc=this.hc=h;this.Lb=j;this.zb=this.ec=this.yc=this.Da=d;this.Ja=15E3;this.lb=d;this.nb=this.ob=0;this.Mb=j;this.ke=this.lc=this.Eb=0;this.fc=j;if(!this.Ra||this.Ra.length===0)this.Ra=pa(ec(this),3);this.q.create("_chartbeat3",this.Ra,34128E3);var a;(a=this.Yc)&&La(a)?(this.ea=new a(this.a),a=h):a=j;if(a){a=!!this.k[Lb];var b=Yb(!!this.k[Mb]&&a);F(this.k,"pingServer","ping.chartbeat.net");F(this.k,Nb,document.title);F(this.k,B,b);this.k[A]=
this.k[A]?I(this.k[A]):Wb(a);this.k[B]=x(this.k[B]);this.ea.getPlayerType&&F(this.k,"video_type",this.ea.getPlayerType());this.yc=setInterval(v(this.od,this),1E3);if(this.La===h)this.ub=v(this.Dd,this),Ha(window,"message",this.ub),this.lb=setInterval(this.le,1E3);Zc.ia.N.call(this)}};q.Ib=k();
q.na=function(){if(this.ea){if(!dd(this))this.oc=h;if(!this.oc)return u()-this.Ua>=this.tb&&clearInterval(this.Da),Zc.ia.na.call(this);if(this.ea.isReady())this.Lb=this.oc=j,this.ec=ed(this),fd(this),this.Da=setInterval(v(this.Kb,this),100),Zc.ia.na.call(this);else if(!this.Lb){this.Lb=h;if(this.ke++>150)throw"Error: Video strategy never reported its ready state";gd(this,100)}}};
q.Sa=function(){if(this.ea){var a=this.k,b=this.ea,c=b.getState(),e=dd(this),f=this.La?[]:r._cbq||(r._cbq=[]),g=b.getViewStartTime(),l=hd(this),o=b.getAutoplayType?b.getAutoplayType():d,g=g===-1?-1:g/1E3,l=l?encodeURIComponent(l):d;if(!cd.path||cd.path===e||c==="s2"&&cd.state!=="s2")switch(cd={path:e,state:c},f.push(["_vi",Na(id(this))]),f.push(["_vp",e]),f.push(["_vdd",Na(jd(this))]),f.push(["_vs",b.getState()]),b.getContentType&&f.push(["_vt",b.getContentType()]),b.getAdPosition&&f.push(["_vap",
b.getAdPosition()]),f.push(["_vtn",Na(hd(this))]),f.push(["_vd",b.getTotalDuration()]),b.getState()){case O:case "s2":case "s3":f.push(["R","1"]);break;case "s4":f.push(["R","0"])}a=kd(this)+Z("_vt",b.getContentType?b.getContentType():"")+Z("_vap",b.getAdPosition?b.getAdPosition():"")+Z("_vs",c)+Z("_vcs",this.Mb?"1":"0")+Z("_vbr",b.getBitrate?b.getBitrate():"")+Z("_vvs",g)+Z("_vpt",b.getCurrentPlayTime())+Z("_vtn",l)+Z("_vaup",o||"unkn")+Z("_vplt",a.video_type)+Z("_vce",this.lc)+Z("c",Math.round(Sa(this.se)/
600)/100)+"&W=0&R="+(c==="s2"?"1":"0")+"&I="+(c!=="s2"?"1":"0")+"&E="+this.Eb+"&j="+(this.Ja/1E3+15)+ld(this)+"&tz="+(new Date).getTimezoneOffset()+(Vb(this.q)?"&l=1":"")+"&_";this.La===h&&t(f,function(a){window.top.postMessage("cbqpush::"+a.join("::"),"*")});this.hb(a)}};function Z(a,b){return b!==d&&b!==""?"&"+a+"="+b:""}q.fb=function(){this.q.update("_cb_cp",this.Ba,60,j,",")};function ld(a){var b=a.q.D("_cb_cp");a.q.remove("_cb_cp");return b?"&D="+b:""}
function md(a){return a.k.subdomain?a.k.subdomain:x(r.location.hostname)}function jd(a){var b=a.k,a=a.ea,b=b.videodomain||a.getHost&&a.getHost()||b[B];return"video@"+(b&&b.replace(/^video@/,""))}function dd(a){var b=a.sa.videopath;if(b)return b;if(a.k.videoPathHash){if(a=id(a))return pa(a)}else return a.ea.getVideoPath();return""}function id(a){return a.sa.title||a.ea.getTitle()}function hd(a){return a.sa.thumbnailpath||a.ea.getThumbnailPath()}
function kd(a){var b=a.k,c=a.ea,e=c.getUid&&c.getUid()||b.uid,f=Na(jd(a)),g="",l=a.gb?"&b="+a.gb:"",o,n=a.k[A];o=a.k.useSubDomains!==j&&n&&n.substr(0,1)==="/"?md(a)+n:n;var n=c.getSections&&c.getSections(),C=c.getAuthors&&c.getAuthors(),E=b.sections?"&g0="+encodeURIComponent(b.sections):"",Q=b.authors?"&g1="+encodeURIComponent(b.authors):"",n=n===d||b.videoPageGroups?E:"&g0="+encodeURIComponent(n.join(",")),C=C===d||b.videoPageGroups?Q:"&g1="+encodeURIComponent(C.join(",")),Q="",E=dd(a);if(a.zb===
d)a.zb=E;else if(E!=a.zb)Q=Z("D",a.Ba),a.Ba=pa(ec(a)),a.zb=E,a.ob=0,a.nb=0,a.Eb=0,a.lc=0,a.Mb=nd(a)&&!od(a),a.hc=h;if(a.hc||Q){if(a.La===j||a.La===h&&a.Oc===h)a.hc=j;g=(fc(a)?"&v=":"&r=")+gc(a)}a.Eb+=a.ob;a.ob=0;a.lc+=a.nb;a.nb=0;fd(a);var T=E="",fa="",aa="",K="",D="",ha="",ia="";if(!a.La===h||a.fc===h)E="&_vi="+nc(a),T="&_vp="+encodeURIComponent(o),fa="&_vh="+Na(md(a)),aa="&_vdd="+encodeURIComponent(b[B]),a.fc===h?(K=b.u,D=b.t,ha=db(b.v),ia=db(b.r)):(K=J("u"),D=J("t"),ha=db(J("v")),ia=db(J("r")));
o="";o=Ka(ha)?"&_pv="+ha:Ka(ia)?"&_pr="+ia:"&_pr=NA";ha="&_pu=";ia="&_pt=";ha+=K?K:"NA";ia+=D?D:"NA";K=!b.noCookies&&a.q.isSupported();D=c.getStrategyName?c.getStrategyName():"";return Oa()+"//"+b.pingServer+"/ping?h="+f+"&g="+e+"&p="+Na(dd(a))+"&i="+Na(id(a))+n+C+"&u="+a.Ra+"&t="+a.Ba+"&x=0&y=0&V=106"+Z("VS",D)+(K?"&n="+a.Xb:"&nc=1")+l+g+Q+Z("_vd",c.getTotalDuration())+E+T+fa+ha+ia+o+aa}q.Kb=function(){if(nd(this)&&!od(this))this.Mb=h;var a=ed(this);if(this.ec!=a)this.ec=a,fd(this),this.na()};
function fd(a){var b=a.Ja;a.Ja=nd(a)?a.Eb<60?5E3:15E3:$c;b!=a.Ja&&gd(a,a.Ja)}function gd(a,b){clearInterval(a.qb);a.Ja=b;a.qb=setInterval(v(a.na,a),b)}function ed(a){return a.ea.getState()+a.ea.getContentType()}function nd(a){return a.ea.getState()==="s2"||od(a)}function od(a){return a.ea.getContentType()==="ad"}q.od=function(){nd(this)===h&&(this.ob+=1,this.ea.getContentType()===N&&(this.nb+=1))};q.le=function(){window.parent.postMessage("cbdata?","*")};
q.Dd=function(a){if(a.source===window.parent&&(a=a.data,Ka(a)&&a.indexOf("domain=")===0)){this.fc=h;var b={domain:h,uid:h,path:h,title:h,referrer:h,internal:h,subdomain:h,token:h,u:h,t:h,v:h,r:h},c=this;t(a.split("&"),function(a){var a=a.split("="),f=a[0],a=a[1];b[f]&&(c.k[f]=decodeURIComponent(a))});Ia(window,"message",this.ub);clearInterval(this.lb);this.lb=d;this.Oc=h;this.na()}};q.setProperty=function(a,b){var c=j,e=this;t(bd,function(f){if(a.toLowerCase()==f)return e.sa[f]=b,c=h,j});return c};
q.terminate=function(){clearInterval(this.yc);clearInterval(this.lb);clearInterval(this.Da);Ia(window,"message",this.ub);Zc.ia.terminate.call(this)};q.ya=function(){Zc.ia.ya.call(this);this.Yc=this.a=this.ub=i};function $(a){this.a=a;this.G=h;this.F=j;this.B=u();this.Da=this.ua=this.Aa=d;this.ha()}q=$.prototype;q.ha=function(){this.Da=setInterval(s(this.Kb,this),100);var a=this.a.getPlayerState();(a===1||a===2||a===0)&&this.fa()};q.Kb=function(){if(this.a.getPlayerState()===1)clearInterval(this.Da),this.Da=d,this.fa()};q.fa=function(){if(!this.F)this.F=h};function zd(a){var b;return(b=(a=a.a.getVideoUrl())&&a.match(/[?&]v=([^&]+)/),a=b)&&a[1]}q.O=m("G");
q.M=function(){var a="";La(this.a.getVideoData)&&(a=(a=this.a.getVideoData())&&a.title||"");return a};q.J=function(){return zd(this)||this.a.getVideoUrl()};q.U=function(){return N};q.P=p("");q.ca=function(){var a=this.a.getDuration();return Ja(a)?a*1E3:a};q.H=function(){if(!this.F)return O;var a=this.a.getPlayerState();return a===0?"s4":a===2?"s3":"s2"};q.X=function(){var a=this.a.getCurrentTime();return Va(a)};q.T=p(-1);q.ba=function(){return"http://img.youtube.com/vi/"+zd(this)+"/default.jpg"};
q.Z=k();q.S=k();q.da=function(){return isNaN(this.B)?0:Sa(this.B)};q.$=m("Aa");q.Q=m("ua");q.aa=p("YT");$.prototype.getStrategyName=$.prototype.aa;$.prototype.isReady=$.prototype.O;$.prototype.getTitle=$.prototype.M;$.prototype.getVideoPath=$.prototype.J;$.prototype.getContentType=$.prototype.U;$.prototype.getAdPosition=$.prototype.P;$.prototype.getTotalDuration=$.prototype.ca;$.prototype.getState=$.prototype.H;$.prototype.getCurrentPlayTime=$.prototype.X;$.prototype.getBitrate=$.prototype.T;
$.prototype.getThumbnailPath=$.prototype.ba;$.prototype.getPlayerType=$.prototype.Z;$.prototype.getAutoplayType=$.prototype.S;$.prototype.getViewStartTime=$.prototype.da;$.prototype.getSections=$.prototype.$;$.prototype.getAuthors=$.prototype.Q;$.verify=function(a){return La(a.getDuration)&&La(a.getVideoUrl)&&La(a.getVideoEmbedCode)};function Ad(){r._cbv_strategies||(r._cbv_strategies=[]);r._cbv_strategies.push(X);r._cbv_strategies.push(U);r._cbv_strategies.push(S);r._cbv_strategies.push($);r._cbv_strategies.push(V);r._cbv_strategies.push(R);r._cbv_strategies.push(P);r._cbv_strategies.push(W);r._cbv_strategies.push(Y);this.mc=[];this.sa=[];this.k=r._sf_async_config||{};Pb("_cbv",v(this.Ed,this));if(this.k[ad]!==j)this.wd=bb(v(this.Bc,this),5E3),this.Bc(),setTimeout(v(this.Ea,this),3E4)}
Ad.prototype.Ed=function(a){if(ba(a)=="array"&&typeof a[0]=="string"){var b=a[0];if(b==="autoDetectYouTubeIframes"){Bd();return}else if(b==="removePlayer"){Cd(this,a[1]);return}else if(b==="setProps"){Dd(a[1])||this.sa.push(a[1]);return}}Ed(this,a)};function Ed(a,b){var c=j,e=r._cbv_strategies;w(window.jwplayer)&&(b=La(b)?b():b);t(e,function(a){if(a.verify(b))return c=a,j});c&&Fd(a,b,c)}
function Cd(a,b){var c=a.mc,e=r.pSUPERFLY_video,f=Qa(c,function(a){return b===a});f!==-1&&c.splice(f,1);f=Qa(e,function(a){return a.a===b});f!==-1&&e.splice(f,1)[0].ya()}function Dd(a){if(!w(a))return j;var b=a.player,c=Ra(function(a){return a.a===b});return!w(c)?j:Gd(c,a)}function Gd(a,b){var c=j;t(b,function(b,f){if(f!=="player"&&(c=a.setProperty(f,b),!c))return c});return c}
function Fd(a,b,c){var e=j;t(a.mc,function(a){if(b===a)return e=h,j});if(!e){c=new Zc(b,c);r.pSUPERFLY_video.push(c);for(var f=a.sa.length-1;f>-1;f--)Gd(c,a.sa[f])&&a.sa.splice(f,1);jc(c);a.mc.push(b)}}
Ad.prototype.Bc=function(){if(La(window.jwplayer)&&w(window.jwplayer())){this.Ea();for(var a=0,b=window.jwplayer(a);w(b.id);)window._cbv.push(b),b=window.jwplayer(++a)}else{if(window.flowplayer&&(a=window.flowplayer())){this.Ea();window._cbv.push(a);return}window.brightcove&&window.experienceJSON?(this.Ea(),window._cbv.push(window.brightcove)):window.videojs?(this.Ea(),a=window.videojs.plugin,La(a)&&a("chartbeat",function(a){this.cb_configs=a;window._cbv.push(this)})):window.kWidget?(this.Ea(),window.kWidget.addReadyCallback(function(a){window._cbv.push(document.getElementById(a))})):
window.$pdk?(this.Ea(),window._cbv.push(window.$pdk)):t(document.getElementsByTagName("video"),function(a){window._cbv.push(a)})}};Ad.prototype.Ea=function(){Za(this.wd)};
function Bd(){function a(){function a(b){r._cbv.push(b.target)}var b=r.YT.Player;t(document.getElementsByTagName("iframe"),function(f){var g=f.src,l=g&&g.indexOf("www.youtube.com/embed/");g&&l>=0&&l<9&&new b(f,{events:{onReady:a}})})}if(r.YT&&r.YT.Player)a();else{var b=r.onYouTubeIframeAPIReady;r.onYouTubeIframeAPIReady=function(){if(b){try{b.apply(r,arguments)}catch(c){}a()}}}};function Hd(a,b){return function(c,e){if(!Cb){a();var f=r._sf_async_config,g="",l=f[A],l=ta(l);/^\//.test(l)&&(g=x(r.location.hostname));f[Ob]=Oa()+"//"+g+l;if(Ka(c))f[A]=I(c),e&&(f[Nb]=e);else if(Pa(c)){var o=["authors","sections",Nb,A];t(c,function(a,b){if(Qa(o,function(a){return a===b})!==-1||b.indexOf("_")===0)f[b]=b===A?I(a):a})}b()}}};if(!G.D("cb_optout")){if(window.location==window.parent.location&&!r.pSUPERFLY){var Id=new Pc,Jd={};r.pSUPERFLY=Jd;var Kd=!!Gc;Jd.virtualPage=Hd(function(){Id.pb();Kd&&Gc.evps()},function(){Id.Bb();Kd&&Gc.svps()});Jd.activity=v(Id.fd,Id);jc(Id);var Ld=H.Y(h);if(!Ld?0:Ld.getItem("_cb_ip")){var Md=r.location;(!/^(.+[.])?chartbeat\.com$/.test(Md.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(Md.pathname))||Mc()}else Ha(r,"message",Nc)}r.pSUPERFLY_video||(r.pSUPERFLY_video=[]);new Ad};})();
